export const MYSTOCKPROJECTID = 1;
export const MARKETAPI = "http://api.marketstack.com/v1/";
export const MARKETSTOCKSEARCH = `${MARKETAPI}tickers?access_key=${process.env.NEXT_PUBLIC_SUPABASE_MARKETSTACKKEY}`;
export const MARKETSTOCKVOLUME = `${MARKETAPI}eod/latest?access_key=${process.env.NEXT_PUBLIC_SUPABASE_MARKETSTACKKEY}`;
export const MARKETSTOCKDETAIL = `${MARKETAPI}eod?access_key=${process.env.NEXT_PUBLIC_SUPABASE_MARKETSTACKKEY}`;
export const MARKETSTOCKDETAILINTRADAY = `${MARKETAPI}intraday?access_key=${process.env.NEXT_PUBLIC_SUPABASE_MARKETSTACKKEY}`;
export const USERSTABLE = "users";
export const STOCKSTABLE = "stocks";
export const PROJECTTABLE = "projects";
export const MAXSTOCKLIMIT = 10;
export const STOCKFILTER = ["1D", "5D", "1M", "6M", "1Y", "5Y", "MAX"];
