export const stockList = {
  pagination: {
    limit: 100,
    offset: 0,
    count: 31,
    total: 31,
  },
  data: [
    {
      name: "Apple Inc",
      symbol: "AAPL",
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: "NASDAQ Stock Exchange",
        acronym: "NASDAQ",
        mic: "XNAS",
        country: "USA",
        country_code: "US",
        city: "New York",
        website: "www.nasdaq.com",
      },
    },
    {
      name: "APPLE DRN",
      symbol: "AAPL34.BVMF",
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: "B3 - Brasil Bolsa Balcão S.A",
        acronym: "Bovespa",
        mic: "BVMF",
        country: "Brazil",
        country_code: "BR",
        city: "Sao Paulo",
        website: "www.bmfbovespa.com.br",
      },
    },
    {
      name: "APPLE INC",
      symbol: "AAPL.XSGO",
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: "Santiago Stock Exchange",
        acronym: "BVS",
        mic: "XSGO",
        country: "Chile",
        country_code: "CL",
        city: "Santiago",
        website: "www.bolsadesantiago.com",
      },
    },
    {
      name: "APPLE INC",
      symbol: "AAPL.XBOG",
      has_intraday: false,
      has_eod: false,
      country: null,
      stock_exchange: {
        name: "Bolsa de Valores de Colombia",
        acronym: "BVC",
        mic: "XBOG",
        country: "Colombia",
        country_code: "CO",
        city: "Bogota",
        website: "www.bvc.com.co",
      },
    },
    {
      name: "APPLE INC. REGISTERED SHARES O.N.",
      symbol: "APC.XSTU",
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: "Börse Stuttgart",
        acronym: "XSTU",
        mic: "XSTU",
        country: "Germany",
        country_code: "DE",
        city: "Stuttgart",
        website: "www.boerse-stuttgart.de",
      },
    },
    {
      name: "APPLE INC.",
      symbol: "APC.XFRA",
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: "Deutsche Börse",
        acronym: "FSX",
        mic: "XFRA",
        country: "Germany",
        country_code: "DE",
        city: "Frankfurt",
        website: "www.deutsche-boerse.com",
      },
    },
    {
      name: "APPLE INC.",
      symbol: "APC.XETRA",
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: "Deutsche Börse Xetra",
        acronym: "XETR",
        mic: "XETRA",
        country: "Germany",
        country_code: "DE",
        city: "Frankfurt",
        website: "",
      },
    },
    {
      name: "APPLE",
      symbol: "AAPL.XMIL",
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: "Borsa Italiana",
        acronym: "MIL",
        mic: "XMIL",
        country: "Italy",
        country_code: "IT",
        city: "Milano",
        website: "www.borsaitaliana.it",
      },
    },
    {
      name: "APPLE INC",
      symbol: "AAPL.XMEX",
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: "Mexican Stock Exchange",
        acronym: "BMV",
        mic: "XMEX",
        country: "Mexico",
        country_code: "MX",
        city: "Mexico City",
        website: "www.bmv.com.mx",
      },
    },
    {
      name: "APPLE INC",
      symbol: "AAPL.XLIM",
      has_intraday: false,
      has_eod: false,
      country: null,
      stock_exchange: {
        name: "Bolsa de Valores de Lima",
        acronym: "BVL",
        mic: "XLIM",
        country: "Peru",
        country_code: "PE",
        city: "Lima",
        website: "www.bvl.com.pe",
      },
    },
    {
      name: "Apple Hospitality REIT Inc",
      symbol: "APLE",
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: "New York Stock Exchange",
        acronym: "NYSE",
        mic: "XNYS",
        country: "USA",
        country_code: "US",
        city: "New York",
        website: "www.nyse.com",
      },
    },
    {
      name: "Apple Flavor Fragrance Group Company Ltd",
      symbol: "603020.XSHG",
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: "Shanghai Stock Exchange",
        acronym: "SSE",
        mic: "XSHG",
        country: "China",
        country_code: "CN",
        city: "Shanghai",
        website: "www.sse.com.cn",
      },
    },
    {
      name: "APPLE INTERNATIONAL CO LTD",
      symbol: "2788.XTKS",
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: "Tokyo Stock Exchange",
        acronym: "TSE",
        mic: "XTKS",
        country: "Japan",
        country_code: "JP",
        city: "Tokyo",
        website: "www.jpx.co.jp",
      },
    },
    {
      name: "APPLEGREEN PLC ORD EUR0.01",
      symbol: "APGN.XLON",
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: "London Stock Exchange",
        acronym: "LSE",
        mic: "XLON",
        country: "United Kingdom",
        country_code: "GB",
        city: "London",
        website: "www.londonstockexchange.com",
      },
    },
    {
      name: "APPLE INC",
      symbol: "AAPL.XBUE",
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: "Buenos Aires Stock Exchange",
        acronym: "BCBA",
        mic: "XBUE",
        country: "Argentina",
        country_code: "AR",
        city: "Buenos Aires",
        website: "www.bcba.sba.com.ar",
      },
    },
    {
      name: "APPLE INC",
      symbol: "AAPLD.XBUE",
      has_intraday: false,
      has_eod: false,
      country: null,
      stock_exchange: {
        name: "Buenos Aires Stock Exchange",
        acronym: "BCBA",
        mic: "XBUE",
        country: "Argentina",
        country_code: "AR",
        city: "Buenos Aires",
        website: "www.bcba.sba.com.ar",
      },
    },
    {
      name: "Apple Green Holding Inc",
      symbol: "AGPL",
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: "OTC PINK current",
        acronym: "PINK",
        mic: "PINC",
        country: "USA",
        country_code: "US",
        city: "New York",
        website: "www.otcmarkets.com",
      },
    },
    {
      name: "Apple Rush Company Inc",
      symbol: "APRU",
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: "OTC PINK current",
        acronym: "PINK",
        mic: "PINC",
        country: "USA",
        country_code: "US",
        city: "New York",
        website: "www.otcmarkets.com",
      },
    },
    {
      name: "APPLE INC",
      symbol: "AAPL",
      has_intraday: true,
      has_eod: false,
      country: null,
      stock_exchange: {
        name: "Investors Exchange",
        acronym: "IEX",
        mic: "IEXG",
        country: "USA",
        country_code: "US",
        city: "New York",
        website: "www.iextrading.com",
      },
    },
    {
      name: "Apple Green Holding Inc",
      symbol: "AGPL",
      has_intraday: true,
      has_eod: false,
      country: null,
      stock_exchange: {
        name: "Investors Exchange",
        acronym: "IEX",
        mic: "IEXG",
        country: "USA",
        country_code: "US",
        city: "New York",
        website: "www.iextrading.com",
      },
    },
    {
      name: "APPLE HOSPITALITY REIT INC",
      symbol: "APLE",
      has_intraday: true,
      has_eod: false,
      country: null,
      stock_exchange: {
        name: "Investors Exchange",
        acronym: "IEX",
        mic: "IEXG",
        country: "USA",
        country_code: "US",
        city: "New York",
        website: "www.iextrading.com",
      },
    },
    {
      name: "Applegreen plc",
      symbol: "APGN.XSTU",
      has_intraday: false,
      has_eod: true,
      country: "Germany",
      stock_exchange: {
        name: "Börse Stuttgart",
        acronym: "XSTU",
        mic: "XSTU",
        country: "Germany",
        country_code: "DE",
        city: "Stuttgart",
        website: "www.boerse-stuttgart.de",
      },
    },
    {
      name: "Apple Finance Limited",
      symbol: "500014.XBOM",
      has_intraday: false,
      has_eod: true,
      country: "India",
      stock_exchange: {
        name: "Bombay Stock Exchange",
        acronym: "MSE",
        mic: "XBOM",
        country: "India",
        country_code: "IN",
        city: "Mumbai",
        website: "www.bseindia.com",
      },
    },
    {
      name: "APPLE HOSPITALITY REIT",
      symbol: "48T.XFRA",
      has_intraday: false,
      has_eod: true,
      country: "Germany",
      stock_exchange: {
        name: "Deutsche Börse",
        acronym: "FSX",
        mic: "XFRA",
        country: "Germany",
        country_code: "DE",
        city: "Frankfurt",
        website: "www.deutsche-boerse.com",
      },
    },
    {
      name: "APPLE INC. CDR",
      symbol: "APC8.XFRA",
      has_intraday: false,
      has_eod: true,
      country: "Germany",
      stock_exchange: {
        name: "Deutsche Börse",
        acronym: "FSX",
        mic: "XFRA",
        country: "Germany",
        country_code: "DE",
        city: "Frankfurt",
        website: "www.deutsche-boerse.com",
      },
    },
    {
      name: "APPLE DRN",
      symbol: "AAPL34",
      has_intraday: false,
      has_eod: false,
      country: null,
      stock_exchange: {
        name: "Investors Exchange",
        acronym: "IEX",
        mic: "IEXG",
        country: "USA",
        country_code: "US",
        city: "New York",
        website: "www.iextrading.com",
      },
    },
    {
      name: "Apple Flavor Fragrance Group Company Ltd",
      symbol: "603020",
      has_intraday: true,
      has_eod: false,
      country: null,
      stock_exchange: {
        name: "Investors Exchange",
        acronym: "IEX",
        mic: "IEXG",
        country: "USA",
        country_code: "US",
        city: "New York",
        website: "www.iextrading.com",
      },
    },
    {
      name: "APPLE INC",
      symbol: "AAPLD",
      has_intraday: false,
      has_eod: false,
      country: null,
      stock_exchange: {
        name: "Investors Exchange",
        acronym: "IEX",
        mic: "IEXG",
        country: "USA",
        country_code: "US",
        city: "New York",
        website: "www.iextrading.com",
      },
    },
    {
      name: "Apple Rush Comp Inc",
      symbol: "APRU",
      has_intraday: true,
      has_eod: false,
      country: null,
      stock_exchange: {
        name: "Investors Exchange",
        acronym: "IEX",
        mic: "IEXG",
        country: "USA",
        country_code: "US",
        city: "New York",
        website: "www.iextrading.com",
      },
    },
    {
      name: "Apple Inc.",
      symbol: "1AAPL.XMIL",
      has_intraday: false,
      has_eod: true,
      country: "Italy",
      stock_exchange: {
        name: "Borsa Italiana",
        acronym: "MIL",
        mic: "XMIL",
        country: "Italy",
        country_code: "IT",
        city: "Milano",
        website: "www.borsaitaliana.it",
      },
    },
    {
      name: "Apple iSports Group Inc",
      symbol: "AAPI",
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: "OTC PINK current",
        acronym: "PINK",
        mic: "PINC",
        country: "USA",
        country_code: "US",
        city: "New York",
        website: "www.otcmarkets.com",
      },
    },
  ],
};

export const STOCKVOLUMN = {
  pagination: {
    limit: 100,
    offset: 0,
    count: 2,
    total: 2,
  },
  data: [
    {
      open: 15.39,
      high: 15.61,
      low: 15.36,
      close: 15.47,
      volume: 1318232.0,
      adj_high: 15.61,
      adj_low: 15.36,
      adj_close: 15.47,
      adj_open: 15.39,
      adj_volume: 1318236.0,
      split_factor: 1.0,
      dividend: 0.0,
      symbol: "APLE",
      exchange: "XNYS",
      date: "2024-04-23T00:00:00+0000",
    },
    {
      open: 165.35,
      high: 167.05,
      low: 164.92,
      close: 166.9,
      volume: 49537761.0,
      adj_high: 167.05,
      adj_low: 164.92,
      adj_close: 166.9,
      adj_open: 165.35,
      adj_volume: 49537761.0,
      split_factor: 1.0,
      dividend: 0.0,
      symbol: "AAPL",
      exchange: "XNAS",
      date: "2024-04-23T00:00:00+0000",
    },
  ],
};
